### ISSUE TITLE
json empy

### ISSUE THREAD

**Issue by ghost** [orsifrancesco/instagram-without-api-node#2]
Hello,
I use the module on my bot discord.
In local on my pc no problem, but when I put them on my vps the file will be created but it will stay empty just with the array like this [ ].
Any idea of the problem ?  
The problem comes from the fact that I use the headers of windows and not of my server ?

**Comment by orsifrancesco** [comment]
I think the problem is not correlated with the repository but in the way you are using it.. it sounds like you found the problem yourself with your latest sentence :)

**Comment by ghost** [comment]
The problem not having a graphic interface do not see how to do  ?
